[project]
name = "comfyui-evaluate-pack"
description = """Transforms a string with Python code written in the node"""

version = "1.0.0"
license = { file = "LICENSE" }
requires-python = ">=3.12"
dependencies = []

[project.urls]
Repository = "https://github.com/alchemine/comfyui-evaluate-pack"
"Bug Tracker" = "https://github.com/alchemine/comfyui-evaluate-pack/issues"

[tool.comfy]
PublisherId = "alchemine"
DisplayName = "ComfyUI-Evaluate-Pack"
Icon = ""
